alias lha='ls -lha'
alias ossh-log='sudo journalctl -u ossh -f --output cat'
alias ossh-start='sudo service ossh start'
alias ossh-stop='sudo service ossh stop'
alias ossh-restart='sudo service ossh restart'
alias ossh-clear-mounts='for d in $(ls /etc/ossh/ffs/sandboxes/) ; do umount /etc/ossh/ffs/sandboxes/$d/* ; done ; rm -rf /etc/ossh/ffs/sandboxes/*'
