{
 "title": "oSSH Cluster",
 "tags": [ "oSSH" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "ossh_active_sessions" } },
   { "name": "data", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "ossh_active_sessions" } }
  ]
 },
 "panels": [
  {
   "title": "Time online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ossh_time_online{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Time wasted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ossh_time_wasted{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Time wasted / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Commands ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ossh_commands_executed{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ossh_logins{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ossh_active_sessions{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(ossh_known_hosts{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(ossh_known_users{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Passwords",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(ossh_known_passwords{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Payloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(ossh_known_payloads{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "type": "heatmap-new",
   "description": "Shows when and how often data has been added to the nodes. The brighter, the more data has been added at that point in time. (host, user, password, payload)",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(ossh_known_hosts{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "host"
    },
    {
     "expr": "sum(rate(ossh_known_users{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(ossh_known_passwords{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "password"
    },
    {
     "expr": "sum(rate(ossh_known_payloads{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "payload"
    }
   ]
  },
  {
   "type": "heatmap-new",
   "description": "Shows when and how often events happened. The brighter, the more events happened at that point in time. (session created, login finished, command executed)",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(ossh_active_sessions{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "session"
    },
    {
     "expr": "sum(rate(ossh_logins{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "login"
    },
    {
     "expr": "sum(rate(ossh_commands_executed{instance=~\"$node\",job=~\"$job\"}[$__interval]))",
     "legendFormat": "command"
    }
   ]
  },
  { "title": "Nodes: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time online",
   "type": "timeseries",
   "description": "Shows how long the nodes have been online (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ossh_time_online{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time online (avg)"
    },
    {
     "expr": "min(ossh_time_online{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time online (min)"
    },
    {
     "expr": "max(ossh_time_online{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time online (max)"
    }
   ]
  },
  {
   "title": "Time wasted",
   "type": "timeseries",
   "description": "Shows how much bot time the nodes wasted (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ossh_time_wasted{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted (avg)"
    },
    {
     "expr": "min(ossh_time_wasted{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted (min)"
    },
    {
     "expr": "max(ossh_time_wasted{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted (max)"
    }
   ]
  },
  {
   "title": "Time wasted / s",
   "type": "timeseries",
   "description": "Shows how much bot time the nodes wasted per second (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted / s (avg)"
    },
    {
     "expr": "min(ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted / s (min)"
    },
    {
     "expr": "max(ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "time wasted / s (max)"
    }
   ]
  },
  {
   "title": "Commands / s",
   "type": "timeseries",
   "description": "Shows how many commands the nodes are executing per second (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "avg(ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "commands / s (avg)"
    },
    {
     "expr": "min(ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "commands / s (min)"
    },
    {
     "expr": "max(ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "commands / s (max)"
    }
   ]
  },
  {
   "title": "Logins / s",
   "type": "timeseries",
   "description": "Shows how many times bots tried to login on the nodes (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg(ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "logins (avg)"
    },
    {
     "expr": "min(ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "logins (min)"
    },
    {
     "expr": "max(ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "logins (max)"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Shows how many sessions are open on the nodes (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "avg(ossh_active_sessions{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sessions (avg)"
    },
    {
     "expr": "min(ossh_active_sessions{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sessions (min)"
    },
    {
     "expr": "max(ossh_active_sessions{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "sessions (max)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows how many goroutines are active on the nodes (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "avg(go_goroutines{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "goroutines (avg)"
    },
    {
     "expr": "min(go_goroutines{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "goroutines (min)"
    },
    {
     "expr": "max(go_goroutines{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "goroutines (max)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "description": "Shows how much RAM the nodes use (avg, min, max)",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM (avg)"
    },
    {
     "expr": "min(process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM (min)"
    },
    {
     "expr": "max(process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM (max)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ossh_time_online{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ossh_time_wasted{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "ossh_active_sessions{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Stacked view of all nodes",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Time online",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_online{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time online"
      }
     ]
    },
    {
     "title": "Time wasted",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_wasted{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time wasted"
      }
     ]
    },
    {
     "title": "Time wasted / s",
     "type": "timeseries",
     "description": "Shows the ratio between time wasted and time online. Higher values = better.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time wasted / s"
      }
     ]
    },
    {
     "title": "Commands / s",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 24 },
     "targets": [
      {
       "expr": "ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "commands / s"
      }
     ]
    },
    {
     "title": "Logins / s",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "logins / s"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 24 },
     "targets": [
      {
       "expr": "ossh_active_sessions{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "sessions"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 24 },
     "targets": [
      {
       "expr": "go_goroutines{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "goroutines"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "RAM"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_online{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time online"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_wasted{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time wasted"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ossh_time_wasted_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "time wasted / s"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ossh_commands_executed_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "commands / s"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ossh_logins_per_second{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "logins"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ossh_active_sessions{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "sessions"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "goroutines"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "RAM"
      }
     ]
    }
   ]
  }
 ]
}