---
- name: Update sshd
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    force: yes
  tags: install

- name: Reload sshd
  service:
    name: sshd
    state: reloaded
  tags: install
